{
 "title": "TXBenchNE",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "txbench_client" },
   { "name": "component", "query": "txbench_client" },
   { "name": "host", "query": ".*1000[56].*" }
  ]
 },
 "panels": [
  {
   "title": "Client Request Rate Req/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_session_total_count{job=~\"$job\"}[10s])"
    }
   ]
  },
  {
   "title": "Client Rate GBit/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_session_total_bytes{job=~\"$job\"}[10s])*8/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Client Request Latency in MicroSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(${component}_session_request_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(${component}_session_request_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(${component}_session_request_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(${component}_session_request_latency_bucket[15s])) by(le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Client Pipeline Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_session_pipeline_depth{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Client Request Latencies Per Shard in MicroSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, irate(${component}_session_request_latency_bucket[15s]))",
     "legendFormat": "p50 shard={{shard}}"
    },
    {
     "expr": "histogram_quantile(0.9, irate(${component}_session_request_latency_bucket[15s]))",
     "legendFormat": "p90 shard={{shard}}"
    },
    {
     "expr": "histogram_quantile(0.99, irate(${component}_session_request_latency_bucket[15s]))",
     "legendFormat": "p99 shard={{shard}}"
    },
    {
     "expr": "histogram_quantile(0.999, irate(${component}_session_request_latency_bucket[15s]))",
     "legendFormat": "p99.9 shard={{shard}}"
    }
   ]
  },
  {
   "title": "Client Pipeline MBytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_session_pipeline_bytes{job=~\"$job\"}/(1024*1024)"
    }
   ]
  },
  {
   "title": "Client Configured ACK Batch Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_session_ack_batch_size{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "K2 RDMA Tx Batch Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_rdma_stack_send_batch_size{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Client Session ID",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "${component}_session_session_id{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "K2 RDMA Tx Msg Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_rdma_stack_send_count{instance=~\"$host\",job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "K2 RDMA Rx Batch Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_rdma_stack_recv_batch_size{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPP Exceptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_reactor_cpp_exceptions{job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "K2 RDMA Rx Msg Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_rdma_stack_recv_count{instance=~\"$host\",job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "K2 RDMA Tx Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_rdma_stack_send_queue_size{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "RDMA Tx GBits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$host\"}[10m])*8/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "RDMA Rx GBits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{instance=~\"$host\"}[10m])*8/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "RDMA packets TX/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_packets_transmitted_total{device=\"mlx5_1\",instance=~\"$host\"}[30s])"
    }
   ]
  },
  {
   "title": "RDMA packets RX/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_packets_received_total{device=\"mlx5_1\",instance=~\"$host\"}[30s])"
    }
   ]
  },
  {
   "title": "Network Rx Packet Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "Network Tx Packet Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "Memory: malloc live objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_memory_malloc_live_objects{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_reactor_utilization{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory: Malloc Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_memory_malloc_operations{job=~\"$job\"}[15s])"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_reactor_cpu_busy_ms{job=~\"$job\"}[15s])"
    }
   ]
  },
  {
   "title": "Memory: Cross CPU Frees",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_memory_cross_cpu_free_operations{job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "CPU Steal Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_reactor_cpu_steal_time_ms{job=~\"$job\"}[15s])"
    }
   ]
  },
  {
   "title": "Mem HugePages Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "% time spent in system calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "Mem HugePages Rsvd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Rsvd{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "% time spent in user space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode=\"user\",instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "Mem HugePages  Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Scaling Frequency GHz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=~\"$host\"}/1000000000"
    }
   ]
  },
  {
   "title": "Mem Cached GB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$host\"}/(1024*1024*1024)"
    }
   ]
  }
 ]
}