# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k2bdto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='k2bdto.proto',
  package='k2bdto',
  syntax='proto3',
  serialized_pb=_b('\n\x0ck2bdto.proto\x12\x06k2bdto\"\xb1\x03\n\x07Request\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\nsequenceId\x18\x03 \x01(\x04\x12,\n\toperation\x18\x04 \x01(\x0b\x32\x19.k2bdto.Request.Operation\x1a\xd2\x02\n\tOperation\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12,\n\x04type\x18\x02 \x01(\x0e\x32\x1e.k2bdto.Request.Operation.Type\x12,\n\x04load\x18\x03 \x01(\x0b\x32\x1e.k2bdto.Request.Operation.Load\x1a\x81\x01\n\x04Load\x12<\n\x0c\x64istribution\x18\x01 \x01(\x0e\x32&.k2bdto.Request.Operation.Distribution\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\x12\x0b\n\x03tps\x18\x03 \x01(\r\x12\x10\n\x08\x64uration\x18\x05 \x01(\x04\x12\r\n\x05\x63ycle\x18\x04 \x01(\x08\";\n\x04Type\x12\x08\n\x04LIST\x10\x00\x12\t\n\x05PRIME\x10\x01\x12\x07\n\x03GET\x10\x02\x12\t\n\x05PAUSE\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\"\x1a\n\x0c\x44istribution\x12\n\n\x06RANDOM\x10\x00\"\x94\x01\n\x08Response\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\nsequenceId\x18\x02 \x01(\x04\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\'\n\x06status\x18\x04 \x01(\x0e\x32\x17.k2bdto.Response.Status\x12\x0f\n\x07message\x18\x05 \x01(\t\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_OPERATION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='k2bdto.Request.Operation.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAUSE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=371,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_OPERATION_TYPE)

_REQUEST_OPERATION_DISTRIBUTION = _descriptor.EnumDescriptor(
  name='Distribution',
  full_name='k2bdto.Request.Operation.Distribution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RANDOM', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=432,
  serialized_end=458,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_OPERATION_DISTRIBUTION)

_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='k2bdto.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=582,
  serialized_end=609,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)


_REQUEST_OPERATION_LOAD = _descriptor.Descriptor(
  name='Load',
  full_name='k2bdto.Request.Operation.Load',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distribution', full_name='k2bdto.Request.Operation.Load.distribution', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='k2bdto.Request.Operation.Load.count', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tps', full_name='k2bdto.Request.Operation.Load.tps', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='k2bdto.Request.Operation.Load.duration', index=3,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='k2bdto.Request.Operation.Load.cycle', index=4,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=369,
)

_REQUEST_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='k2bdto.Request.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='k2bdto.Request.Operation.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='k2bdto.Request.Operation.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load', full_name='k2bdto.Request.Operation.load', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_OPERATION_LOAD, ],
  enum_types=[
    _REQUEST_OPERATION_TYPE,
    _REQUEST_OPERATION_DISTRIBUTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=458,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='k2bdto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='k2bdto.Request.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequenceId', full_name='k2bdto.Request.sequenceId', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='k2bdto.Request.operation', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_OPERATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=458,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='k2bdto.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='k2bdto.Response.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequenceId', full_name='k2bdto.Response.sequenceId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='k2bdto.Response.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='k2bdto.Response.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='k2bdto.Response.message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=609,
)

_REQUEST_OPERATION_LOAD.fields_by_name['distribution'].enum_type = _REQUEST_OPERATION_DISTRIBUTION
_REQUEST_OPERATION_LOAD.containing_type = _REQUEST_OPERATION
_REQUEST_OPERATION.fields_by_name['type'].enum_type = _REQUEST_OPERATION_TYPE
_REQUEST_OPERATION.fields_by_name['load'].message_type = _REQUEST_OPERATION_LOAD
_REQUEST_OPERATION.containing_type = _REQUEST
_REQUEST_OPERATION_TYPE.containing_type = _REQUEST_OPERATION
_REQUEST_OPERATION_DISTRIBUTION.containing_type = _REQUEST_OPERATION
_REQUEST.fields_by_name['operation'].message_type = _REQUEST_OPERATION
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE_STATUS.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), dict(

    Load = _reflection.GeneratedProtocolMessageType('Load', (_message.Message,), dict(
      DESCRIPTOR = _REQUEST_OPERATION_LOAD,
      __module__ = 'k2bdto_pb2'
      # @@protoc_insertion_point(class_scope:k2bdto.Request.Operation.Load)
      ))
    ,
    DESCRIPTOR = _REQUEST_OPERATION,
    __module__ = 'k2bdto_pb2'
    # @@protoc_insertion_point(class_scope:k2bdto.Request.Operation)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'k2bdto_pb2'
  # @@protoc_insertion_point(class_scope:k2bdto.Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.Operation)
_sym_db.RegisterMessage(Request.Operation.Load)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'k2bdto_pb2'
  # @@protoc_insertion_point(class_scope:k2bdto.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
