---
name: "np1"
nodes_count: 1
#nodes_cpu_set: "30"
#pool_cpu_set: "18,19"
address: "0.0.0.0"
nodes_minimum_port: 11312
monitorEnabled: false
#rdmaEnabled: true
#hugepages: true
#memory: "10G"
#nic_id: "mlx5_0"
