pipeline {
    agent any
    stages {
        stage('Checkout') {
            agent {label "builder"}
            steps {
                echo "\u2600 Getting source"
                // Get code
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/master']],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [[$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: true, recursiveSubmodules: true, reference: '', trackingSubmodules: false]],
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: 'fb82a473-e4f4-4f14-b0d5-0f28af79d0ca', url: 'git@rnd-github-usa-g.huawei.com:SeattleCloudBU/DFV_K2_Platform.git']]
                        ])
            }
        }
        stage('Build Builder Image') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building Docker Builder Image"
                sh "make -C K2Build builder_img_build"
                sh "make -C K2Build builder_img_push"
            }
        }
        stage('Build') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Build"
                sh "./K2Build/k2build make -j -C K2Build"
            }
        }
        stage('Test') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Run K2 Platform Integration Test"
                sh "./K2Build/k2build make -j -C K2Build test"
                sh "./K2Build/k2build /build/build/src/node/node_pool"
                sh "./K2Build/k2build ./test/node_test"
                sh "cat /tmp/node_pool_container_id | xargs docker kill && rm /tmp/node_pool_container_id"
            }
        }
        stage('Install') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Install"
                sh "./K2Build/k2build make -j -C K2Build install"
            }
        }
        stage('Package') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Package"
                sh "./K2Build/k2build make -C K2Build package"
            }
        }
        stage('Upload artifacts') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Uploading artifacts"
                sh "curl http://k2-bvu-10001.huawei.com:10080/incoming/ --upload-file k2platform_*.deb"
                sh "curl http://k2-bvu-10001.huawei.com:10080/incoming/ --upload-file k2platform_*.changes"
            }
        }
    }
}
