#!/bin/bash
echo "*******************************************************************"
echo "* To see package-specific build commands, look in the Jenkinsfile *"
echo "*******************************************************************"
topname=$(dirname "$0")
cd ${topname}/..

echo ">>> Using docker"
IMG_NAME=$(make -pn -C K2Build/Builder | grep "^IMG_NAME" | cut -f 2 -d "=" | tr -d " ")
FULL_IMG_NAME="k2-bvu-10001.huawei.com/${IMG_NAME}:latest"
# set interactive docker only if we're running inside a terminal
if [ -t 1 ] ; then IT=-it; else IT=; fi
echo ">>> Pulling latest builder image: ${FULL_IMG_NAME}"
docker pull ${FULL_IMG_NAME}
echo ">>> Executing command \"$*\" in the build container"
docker run --init --rm ${IT} -v "${PWD}:/build" --cap-add=SYS_PTRACE --security-opt seccomp=unconfined ${FULL_IMG_NAME} $*;

#!/bin/bash

hugeadm --pool-pages-min 2MB:14000
ip link set ens7f0 mtu 9042
ip link set ens7f1 mtu 9042
echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo 0 > /proc/sys/kernel/numa_balancing
echo 0 > /proc/sys/kernel/watchdog
echo 0 > /proc/sys/kernel/nmi_watchdog
for i in {30..39}
do
    echo 0 > /sys/devices/system/machinecheck/machinecheck${i}/check_interval
done
echo 5 > /proc/sys/vm/stat_interval
swapoff -a
