#!/bin/bash
echo "*******************************************************************"
echo "* To see package-specific build commands, look in the Jenkinsfile *"
echo "*******************************************************************"
topname=$(dirname "$0")
cd ${topname}/..

echo ">>> Using docker"
IMG_NAME=$(make -pn -C K2Build/Builder | grep "^IMG_NAME" | cut -f 2 -d "=" | tr -d " ")
FULL_IMG_NAME="k2-bvu-10001.huawei.com/${IMG_NAME}:latest"
# set interactive docker only if we're running inside a terminal
if [ -t 1 ] ; then IT=-it; else IT=; fi
echo ">>> Pulling latest builder image: ${FULL_IMG_NAME}"
docker pull ${FULL_IMG_NAME}
echo ">>> Executing command \"$*\" in the build container"
docker run -p 8088:8088 --init --rm ${IT} -v "${PWD}:/build" ${FULL_IMG_NAME} $*;
