#!/bin/bash
echo "*******************************************************************"
echo "* To see package-specific build commands, look in the Jenkinsfile *"
echo "*******************************************************************"
topname=$(dirname "$0")
cd ${topname}/..

echo ">>> Using docker"
IMG_NAME=$(make -pn -C K2Build/Builder | grep "^IMG_NAME" | cut -f 2 -d "=" | tr -d " ")
FULL_IMG_NAME="k2-bvu-10001.huawei.com/${IMG_NAME}:latest"
# set interactive docker only if we're running inside a terminal
if [ -t 1 ] ; then IT=-it; else IT=; fi
echo ">>> Pulling latest builder image: ${FULL_IMG_NAME}"
docker pull ${FULL_IMG_NAME}
echo ">>> Executing command \"$*\" in the build container"
# TODO: use swarm to setup the integrate test env
if [ $1 == "/build/build/src/node/node_pool" ] ; then
	docker run --privileged --init --rm ${IT} -v "${PWD}:/build" -d --ip="192.168.7.7" --net k2 --cidfile /tmp/node_pool_container_id ${FULL_IMG_NAME} $*;
else
	docker run --privileged --init --rm ${IT} -v "${PWD}:/build" --net k2 ${FULL_IMG_NAME} $*;
fi
