---
id: "1234567890"
nodes_count: 1
#nodes_cpu_set: "30"
#pool_cpu_set: "18,19"
address: "0.0.0.0"
nodes_minimum_port: 13000
monitorEnabled: false
rdmaEnabled: false
#hugepages: true
#memory: "10G"
#nic_id: "mlx5_0"
