---
schema: "2019-07" # required version of the configuration schema
instance-version: 123456 # required version of the configuration instance, monotonically increasing integer
cluster-name: "mysql-backend-na" # optional field with the name of the cluster

partition-manager: # optional partition manager for partition and configuration updates
    endpoints: # required list of partition manager endpoints
        - "tcp+k2rpc://192.168.124.1:1400"
        - "rrdma+k2rpc://[fe80::9a03:9bff:fe89:13ba]:128"

transport-base: &transport-base
    rdma:
        nic_id: "mlx5_0"
    tcp:
        address: "0.0.0.0"
        port: 1000

node-pool-base: &node-pool-base
    node-count: 2
    enable-monitoring: false
    transport:
        <<: *transport-base

node-base: &node-base
    transport:
        <<: *transport-base
        tcp:
            port: 2000

node-pools:
    -   id: "np1"
        <<: *node-pool-base
        node-count: 3
        nodes:
            -   id: 0
                <<: *node-base
                cpu: 15
            -   id: 1
                <<: *node-base
                transport:
                    tcp:
                        port: 3000
    -   id: "np2"
        <<: *node-pool-base

cluster:
    -   host: "host1.futurewei.com"
        node-pools:
            -   id: "np1"
                transport:
                    tcp:
                        address: "192.168.200.1"
                nodes:
                    -   id: 0
                        partitions: [ "1.1.1", "2.1.1" ]
                        transport:
                            rdma:
                                address: "host1.local"
                                port: 246
