---
schema: "2019-07" # required version of the configuration schema
instance-version: 123456 # required version of the configuration instance, monotonically increasing integer
cluster-name: "mysql-backend-na" # optional field with the name of the cluster

partition-manager: # optional partition manager for partition and configuration updates
    endpoints: # required list of partition manager endpoints
        - "tcp+k2rpc://192.168.124.1:1400"
        - "rrdma+k2rpc://[fe80::9a03:9bff:fe89:13ba]:128"

transport-base: &transport-base
    rdma:
        nic_id: "mlx5_0"
    tcp:
        address: "0.0.0.0"
        port: 14000

node-pool-base: &node-pool-base
    node-count: 1
    enable-monitoring: false
    transport:
        <<: *transport-base

node-base: &node-base
    transport:
        <<: *transport-base

node-pools:
    -   id: "np1"
        <<: *node-pool-base

cluster:
    -   host: "host1"
        node-pools:
            -   id: "np1"
                nodes:
                    -   id: 0
                        partitions:
                            -   id: "1.1.1"
                                range: "[a-g)"
                            -   id: "2.1.1"
                                range: "g)"
                        transport:
                            tcp:
                                address: "192.168.200.1"
                                