---
schema: "2019-07" # required version of the configuration schema
instance_version: 123456 # required version of the configuration instance, monotonically increasing integer
cluster_name: "mysql-backend-na" # optional field with the name of the cluster

partition_manager: # optional partition manager for partition and configuration updates
    endpoints: # required list of partition manager endpoints
        - "tcp+k2rpc://192.168.124.1:1400"
        - "rrdma+k2rpc://[fe80::9a03:9bff:fe89:13ba]:128"

transport-base: &transport-base
    rdma:
        nic_id: "mlx5_0"
    tcp:
        address: "0.0.0.0"
        port: 11311

node-pool-base: &node-pool-base
    node_count: 1
    enable_monitoring: false
    enable_hugepages: true
    memory_size: "10G"
    transport:
        <<: *transport-base

node-base: &node-base
    transport:
        <<: *transport-base

node_pools:
    -   id: "np1"
        <<: *node-pool-base

cluster:
    -   host: "host1"
        node_pools:
            -   id: "np1"
                nodes:
                    -   id: 0
                        partitions:
                            -   id: "1.1.1"
                                range: "-"
                        transport:
                            tcp:
                                address: "192.168.200.1"
