/*
MIT License

Copyright(c) 2020 Futurewei Cloud

    Permission is hereby granted,
    free of charge, to any person obtaining a copy of this software and associated documentation files(the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions :

    The above copyright notice and this permission notice shall be included in all copies
    or
    substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS",
    WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
    DAMAGES OR OTHER
    LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
*/

/* This entire file has been generated by common/gen_macros.py" */

#pragma once
#include "MacroUtils.h"
    
// _K2_MKLIST(...) generates a list for formatting variables, e.g. _K2_MKLIST(a, b, c) -> "a" = a, "b" = b, "c" = c
#define _K2_MKLIST(...) _K2_OVERLOADED_MACRO(_K2_MKLIST, __VA_ARGS__)
#define _K2_MKLIST0()
#define _K2_MKLIST1(a1) #a1 "=a1"
#define _K2_MKLIST2(a1,a2) _K2_MKLIST1(a1) ", " _K2_MKLIST1(a2)
#define _K2_MKLIST3(a1,a2,a3) _K2_MKLIST2(a1,a2) ", " _K2_MKLIST1(a3)
#define _K2_MKLIST4(a1,a2,a3,a4) _K2_MKLIST3(a1,a2,a3) ", " _K2_MKLIST1(a4)
#define _K2_MKLIST5(a1,a2,a3,a4,a5) _K2_MKLIST4(a1,a2,a3,a4) ", " _K2_MKLIST1(a5)
#define _K2_MKLIST6(a1,a2,a3,a4,a5,a6) _K2_MKLIST5(a1,a2,a3,a4,a5) ", " _K2_MKLIST1(a6)
#define _K2_MKLIST7(a1,a2,a3,a4,a5,a6,a7) _K2_MKLIST6(a1,a2,a3,a4,a5,a6) ", " _K2_MKLIST1(a7)
#define _K2_MKLIST8(a1,a2,a3,a4,a5,a6,a7,a8) _K2_MKLIST7(a1,a2,a3,a4,a5,a6,a7) ", " _K2_MKLIST1(a8)
#define _K2_MKLIST9(a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_MKLIST8(a1,a2,a3,a4,a5,a6,a7,a8) ", " _K2_MKLIST1(a9)
#define _K2_MKLIST10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_MKLIST9(a1,a2,a3,a4,a5,a6,a7,a8,a9) ", " _K2_MKLIST1(a10)
#define _K2_MKLIST11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_MKLIST10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) ", " _K2_MKLIST1(a11)
#define _K2_MKLIST12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_MKLIST11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) ", " _K2_MKLIST1(a12)
#define _K2_MKLIST13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_MKLIST12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) ", " _K2_MKLIST1(a13)
#define _K2_MKLIST14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_MKLIST13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) ", " _K2_MKLIST1(a14)
#define _K2_MKLIST15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_MKLIST14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) ", " _K2_MKLIST1(a15)
#define _K2_MKLIST16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_MKLIST15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) ", " _K2_MKLIST1(a16)
#define _K2_MKLIST17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_MKLIST16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) ", " _K2_MKLIST1(a17)
#define _K2_MKLIST18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_MKLIST17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) ", " _K2_MKLIST1(a18)
#define _K2_MKLIST19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_MKLIST18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) ", " _K2_MKLIST1(a19)
#define _K2_MKLIST20(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20) _K2_MKLIST19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) ", " _K2_MKLIST1(a20)

// _K2_MKVARS(...) generates a list for formatting variables, e.g. _K2_MKVARS(a, b, c) -> o.a, o.b, o.c
#define _K2_MKVARS(...) _K2_OVERLOADED_MACRO(_K2_MKVARS, __VA_ARGS__)
#define _K2_MKVARS0()
#define _K2_MKVARS1(a1) , o.a1
#define _K2_MKVARS2(a1,a2) _K2_MKVARS1(a1) _K2_MKVARS1(a2)
#define _K2_MKVARS3(a1,a2,a3) _K2_MKVARS2(a1,a2) _K2_MKVARS1(a3)
#define _K2_MKVARS4(a1,a2,a3,a4) _K2_MKVARS3(a1,a2,a3) _K2_MKVARS1(a4)
#define _K2_MKVARS5(a1,a2,a3,a4,a5) _K2_MKVARS4(a1,a2,a3,a4) _K2_MKVARS1(a5)
#define _K2_MKVARS6(a1,a2,a3,a4,a5,a6) _K2_MKVARS5(a1,a2,a3,a4,a5) _K2_MKVARS1(a6)
#define _K2_MKVARS7(a1,a2,a3,a4,a5,a6,a7) _K2_MKVARS6(a1,a2,a3,a4,a5,a6) _K2_MKVARS1(a7)
#define _K2_MKVARS8(a1,a2,a3,a4,a5,a6,a7,a8) _K2_MKVARS7(a1,a2,a3,a4,a5,a6,a7) _K2_MKVARS1(a8)
#define _K2_MKVARS9(a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_MKVARS8(a1,a2,a3,a4,a5,a6,a7,a8) _K2_MKVARS1(a9)
#define _K2_MKVARS10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_MKVARS9(a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_MKVARS1(a10)
#define _K2_MKVARS11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_MKVARS10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_MKVARS1(a11)
#define _K2_MKVARS12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_MKVARS11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_MKVARS1(a12)
#define _K2_MKVARS13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_MKVARS12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_MKVARS1(a13)
#define _K2_MKVARS14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_MKVARS13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_MKVARS1(a14)
#define _K2_MKVARS15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_MKVARS14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_MKVARS1(a15)
#define _K2_MKVARS16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_MKVARS15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_MKVARS1(a16)
#define _K2_MKVARS17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_MKVARS16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_MKVARS1(a17)
#define _K2_MKVARS18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_MKVARS17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_MKVARS1(a18)
#define _K2_MKVARS19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_MKVARS18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_MKVARS1(a19)
#define _K2_MKVARS20(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20) _K2_MKVARS19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_MKVARS1(a20)

// _K2_FROM_JSON(...) generates from-json entries, e.g. _K2_FROM_JSON(a) -> j.at("a").get_to(o.a);
#define _K2_FROM_JSON(...) _K2_OVERLOADED_MACRO(_K2_FROM_JSON, __VA_ARGS__)
#define _K2_FROM_JSON0() (void)o; (void)j;
#define _K2_FROM_JSON1(a1) j.at(#a1).get_to(o.a1);
#define _K2_FROM_JSON2(a1,a2) _K2_FROM_JSON1(a1) _K2_FROM_JSON1(a2)
#define _K2_FROM_JSON3(a1,a2,a3) _K2_FROM_JSON2(a1,a2) _K2_FROM_JSON1(a3)
#define _K2_FROM_JSON4(a1,a2,a3,a4) _K2_FROM_JSON3(a1,a2,a3) _K2_FROM_JSON1(a4)
#define _K2_FROM_JSON5(a1,a2,a3,a4,a5) _K2_FROM_JSON4(a1,a2,a3,a4) _K2_FROM_JSON1(a5)
#define _K2_FROM_JSON6(a1,a2,a3,a4,a5,a6) _K2_FROM_JSON5(a1,a2,a3,a4,a5) _K2_FROM_JSON1(a6)
#define _K2_FROM_JSON7(a1,a2,a3,a4,a5,a6,a7) _K2_FROM_JSON6(a1,a2,a3,a4,a5,a6) _K2_FROM_JSON1(a7)
#define _K2_FROM_JSON8(a1,a2,a3,a4,a5,a6,a7,a8) _K2_FROM_JSON7(a1,a2,a3,a4,a5,a6,a7) _K2_FROM_JSON1(a8)
#define _K2_FROM_JSON9(a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_FROM_JSON8(a1,a2,a3,a4,a5,a6,a7,a8) _K2_FROM_JSON1(a9)
#define _K2_FROM_JSON10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_FROM_JSON9(a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_FROM_JSON1(a10)
#define _K2_FROM_JSON11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_FROM_JSON10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_FROM_JSON1(a11)
#define _K2_FROM_JSON12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_FROM_JSON11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_FROM_JSON1(a12)
#define _K2_FROM_JSON13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_FROM_JSON12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_FROM_JSON1(a13)
#define _K2_FROM_JSON14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_FROM_JSON13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_FROM_JSON1(a14)
#define _K2_FROM_JSON15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_FROM_JSON14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_FROM_JSON1(a15)
#define _K2_FROM_JSON16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_FROM_JSON15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_FROM_JSON1(a16)
#define _K2_FROM_JSON17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_FROM_JSON16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_FROM_JSON1(a17)
#define _K2_FROM_JSON18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_FROM_JSON17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_FROM_JSON1(a18)
#define _K2_FROM_JSON19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_FROM_JSON18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_FROM_JSON1(a19)
#define _K2_FROM_JSON20(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20) _K2_FROM_JSON19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_FROM_JSON1(a20)

// _K2_TO_JSON(...) generates from-json entries, e.g. _K2_TO_JSON(a1, a2) -> {"a1", o.a1}, {"a2", o.a2}
#define _K2_TO_JSON(...) _K2_OVERLOADED_MACRO(_K2_TO_JSON, __VA_ARGS__)
#define _K2_TO_JSON0()
#define _K2_TO_JSON1(a1) {#a1, o.a1}
#define _K2_TO_JSON2(a1,a2) _K2_TO_JSON1(a1) ,  _K2_TO_JSON1(a2)
#define _K2_TO_JSON3(a1,a2,a3) _K2_TO_JSON2(a1,a2) ,  _K2_TO_JSON1(a3)
#define _K2_TO_JSON4(a1,a2,a3,a4) _K2_TO_JSON3(a1,a2,a3) ,  _K2_TO_JSON1(a4)
#define _K2_TO_JSON5(a1,a2,a3,a4,a5) _K2_TO_JSON4(a1,a2,a3,a4) ,  _K2_TO_JSON1(a5)
#define _K2_TO_JSON6(a1,a2,a3,a4,a5,a6) _K2_TO_JSON5(a1,a2,a3,a4,a5) ,  _K2_TO_JSON1(a6)
#define _K2_TO_JSON7(a1,a2,a3,a4,a5,a6,a7) _K2_TO_JSON6(a1,a2,a3,a4,a5,a6) ,  _K2_TO_JSON1(a7)
#define _K2_TO_JSON8(a1,a2,a3,a4,a5,a6,a7,a8) _K2_TO_JSON7(a1,a2,a3,a4,a5,a6,a7) ,  _K2_TO_JSON1(a8)
#define _K2_TO_JSON9(a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_TO_JSON8(a1,a2,a3,a4,a5,a6,a7,a8) ,  _K2_TO_JSON1(a9)
#define _K2_TO_JSON10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_TO_JSON9(a1,a2,a3,a4,a5,a6,a7,a8,a9) ,  _K2_TO_JSON1(a10)
#define _K2_TO_JSON11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_TO_JSON10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) ,  _K2_TO_JSON1(a11)
#define _K2_TO_JSON12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_TO_JSON11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) ,  _K2_TO_JSON1(a12)
#define _K2_TO_JSON13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_TO_JSON12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) ,  _K2_TO_JSON1(a13)
#define _K2_TO_JSON14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_TO_JSON13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) ,  _K2_TO_JSON1(a14)
#define _K2_TO_JSON15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_TO_JSON14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) ,  _K2_TO_JSON1(a15)
#define _K2_TO_JSON16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_TO_JSON15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) ,  _K2_TO_JSON1(a16)
#define _K2_TO_JSON17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_TO_JSON16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) ,  _K2_TO_JSON1(a17)
#define _K2_TO_JSON18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_TO_JSON17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) ,  _K2_TO_JSON1(a18)
#define _K2_TO_JSON19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_TO_JSON18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) ,  _K2_TO_JSON1(a19)
#define _K2_TO_JSON20(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20) _K2_TO_JSON19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) ,  _K2_TO_JSON1(a20)

// _K2_TO_STRING_LIST(...) converts list of args to list of stringed args, e.g. _K2_TO_STRING_LIST(a1, a2) -> "a1", "a2"
#define _K2_TO_STRING_LIST(...) _K2_OVERLOADED_MACRO(_K2_TO_STRING_LIST, __VA_ARGS__)
#define _K2_TO_STRING_LIST0()
#define _K2_TO_STRING_LIST1(a1) #a1
#define _K2_TO_STRING_LIST2(a1,a2) _K2_TO_STRING_LIST1(a1) , _K2_TO_STRING_LIST1(a2)
#define _K2_TO_STRING_LIST3(a1,a2,a3) _K2_TO_STRING_LIST2(a1,a2) , _K2_TO_STRING_LIST1(a3)
#define _K2_TO_STRING_LIST4(a1,a2,a3,a4) _K2_TO_STRING_LIST3(a1,a2,a3) , _K2_TO_STRING_LIST1(a4)
#define _K2_TO_STRING_LIST5(a1,a2,a3,a4,a5) _K2_TO_STRING_LIST4(a1,a2,a3,a4) , _K2_TO_STRING_LIST1(a5)
#define _K2_TO_STRING_LIST6(a1,a2,a3,a4,a5,a6) _K2_TO_STRING_LIST5(a1,a2,a3,a4,a5) , _K2_TO_STRING_LIST1(a6)
#define _K2_TO_STRING_LIST7(a1,a2,a3,a4,a5,a6,a7) _K2_TO_STRING_LIST6(a1,a2,a3,a4,a5,a6) , _K2_TO_STRING_LIST1(a7)
#define _K2_TO_STRING_LIST8(a1,a2,a3,a4,a5,a6,a7,a8) _K2_TO_STRING_LIST7(a1,a2,a3,a4,a5,a6,a7) , _K2_TO_STRING_LIST1(a8)
#define _K2_TO_STRING_LIST9(a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_TO_STRING_LIST8(a1,a2,a3,a4,a5,a6,a7,a8) , _K2_TO_STRING_LIST1(a9)
#define _K2_TO_STRING_LIST10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_TO_STRING_LIST9(a1,a2,a3,a4,a5,a6,a7,a8,a9) , _K2_TO_STRING_LIST1(a10)
#define _K2_TO_STRING_LIST11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_TO_STRING_LIST10(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) , _K2_TO_STRING_LIST1(a11)
#define _K2_TO_STRING_LIST12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_TO_STRING_LIST11(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) , _K2_TO_STRING_LIST1(a12)
#define _K2_TO_STRING_LIST13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_TO_STRING_LIST12(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) , _K2_TO_STRING_LIST1(a13)
#define _K2_TO_STRING_LIST14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_TO_STRING_LIST13(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) , _K2_TO_STRING_LIST1(a14)
#define _K2_TO_STRING_LIST15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_TO_STRING_LIST14(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) , _K2_TO_STRING_LIST1(a15)
#define _K2_TO_STRING_LIST16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_TO_STRING_LIST15(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) , _K2_TO_STRING_LIST1(a16)
#define _K2_TO_STRING_LIST17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_TO_STRING_LIST16(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) , _K2_TO_STRING_LIST1(a17)
#define _K2_TO_STRING_LIST18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_TO_STRING_LIST17(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) , _K2_TO_STRING_LIST1(a18)
#define _K2_TO_STRING_LIST19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_TO_STRING_LIST18(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) , _K2_TO_STRING_LIST1(a19)
#define _K2_TO_STRING_LIST20(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20) _K2_TO_STRING_LIST19(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) , _K2_TO_STRING_LIST1(a20)

// _K2_ENUM_IF_STMT(Name, ...) generates an if statement for each arg to fit in the enum-generator
// macro, e.g. _K2_ENUM_IF_STMT(NAME, a1, a2) -> if(str=="a1") return NAME::a1; if (str=="a2")...
        
#define _K2_ENUM_IF_STMT(...) _K2_OVERLOADED_MACRO(_K2_ENUM_IF_STMT, __VA_ARGS__)
#define _K2_ENUM_IF_STMT0()
#define _K2_ENUM_IF_STMT1(NAME)
#define _K2_ENUM_IF_STMT2(NAME,a1) if(str==#a1) return NAME::a1;
#define _K2_ENUM_IF_STMT3(NAME,a1,a2) _K2_ENUM_IF_STMT2(NAME,a1) _K2_ENUM_IF_STMT2(NAME, a2)
#define _K2_ENUM_IF_STMT4(NAME,a1,a2,a3) _K2_ENUM_IF_STMT3(NAME,a1,a2) _K2_ENUM_IF_STMT2(NAME, a3)
#define _K2_ENUM_IF_STMT5(NAME,a1,a2,a3,a4) _K2_ENUM_IF_STMT4(NAME,a1,a2,a3) _K2_ENUM_IF_STMT2(NAME, a4)
#define _K2_ENUM_IF_STMT6(NAME,a1,a2,a3,a4,a5) _K2_ENUM_IF_STMT5(NAME,a1,a2,a3,a4) _K2_ENUM_IF_STMT2(NAME, a5)
#define _K2_ENUM_IF_STMT7(NAME,a1,a2,a3,a4,a5,a6) _K2_ENUM_IF_STMT6(NAME,a1,a2,a3,a4,a5) _K2_ENUM_IF_STMT2(NAME, a6)
#define _K2_ENUM_IF_STMT8(NAME,a1,a2,a3,a4,a5,a6,a7) _K2_ENUM_IF_STMT7(NAME,a1,a2,a3,a4,a5,a6) _K2_ENUM_IF_STMT2(NAME, a7)
#define _K2_ENUM_IF_STMT9(NAME,a1,a2,a3,a4,a5,a6,a7,a8) _K2_ENUM_IF_STMT8(NAME,a1,a2,a3,a4,a5,a6,a7) _K2_ENUM_IF_STMT2(NAME, a8)
#define _K2_ENUM_IF_STMT10(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_ENUM_IF_STMT9(NAME,a1,a2,a3,a4,a5,a6,a7,a8) _K2_ENUM_IF_STMT2(NAME, a9)
#define _K2_ENUM_IF_STMT11(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_ENUM_IF_STMT10(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9) _K2_ENUM_IF_STMT2(NAME, a10)
#define _K2_ENUM_IF_STMT12(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_ENUM_IF_STMT11(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) _K2_ENUM_IF_STMT2(NAME, a11)
#define _K2_ENUM_IF_STMT13(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_ENUM_IF_STMT12(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11) _K2_ENUM_IF_STMT2(NAME, a12)
#define _K2_ENUM_IF_STMT14(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_ENUM_IF_STMT13(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) _K2_ENUM_IF_STMT2(NAME, a13)
#define _K2_ENUM_IF_STMT15(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_ENUM_IF_STMT14(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13) _K2_ENUM_IF_STMT2(NAME, a14)
#define _K2_ENUM_IF_STMT16(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_ENUM_IF_STMT15(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14) _K2_ENUM_IF_STMT2(NAME, a15)
#define _K2_ENUM_IF_STMT17(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_ENUM_IF_STMT16(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15) _K2_ENUM_IF_STMT2(NAME, a16)
#define _K2_ENUM_IF_STMT18(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_ENUM_IF_STMT17(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16) _K2_ENUM_IF_STMT2(NAME, a17)
#define _K2_ENUM_IF_STMT19(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_ENUM_IF_STMT18(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17) _K2_ENUM_IF_STMT2(NAME, a18)
#define _K2_ENUM_IF_STMT20(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19) _K2_ENUM_IF_STMT19(NAME,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18) _K2_ENUM_IF_STMT2(NAME, a19)
