#!/bin/bash
#
#   Script to setup K2 development environment
#

set -e

printf "Setting up dev environment\n"

printf "\n\nInstalling docker\n"
sudo apt-get update
sudo apt-get upgrade
sudo apt install docker.io

cat >/etc/docker/daemon.json <<EOL
{
  "insecure-registries" : ["k2-bvu-10001.huawei.com"]
}
EOL

printf "\n\nAdding user $USER to docker group\n"
sudo usermod -a -G docker $USER

printf "\n\nRestarting docker\n"
systemctl restart docker

printf "\n\nSet up has succesfully finished.\n"
printf "!!!Please, log-out to close you session and log-in again, so changes to your groups can be applied!!!\n"
