#!/bin/bash

build/client assign -p 1.1.1
build/client set -p 1.1.1 -k 1 -v One

build/client assign -p 2.1.1
build/client set -p 2.1.1 -k 2 -v Two

build/client get -p 1.1.1 -k 1
build/client get -p 2.1.1 -k 2

